

on:
  schedule:
    - cron: '0 * * * *'  # every hour, on the hour (UTC)
  workflow_dispatch:      # allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # adjust to your script's requirement

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Run script
        run: python Alert.py
